### ISSUE TITLE
python build.py failed on windows

### ISSUE THREAD

**Issue by SeekPoint** [pmed/v8-nuget#23]
python build.py
.....
 * branch            555c8b467c21e2c4b22d00e87e3faa0431df9ac2 -> FETCH_HEAD
Reset branch 'Branch_555c8b467c21e2c4b22d00e87e3faa0431df9ac2'
Traceback (most recent call last):
  File ".\build.py", line 196, in <module>
    vs_install_dir = os.path.abspath(os.path.join(os.environ['VCINSTALLDIR'], os.pardir))
  File "C:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'VCINSTALLDIR'
PS D:\ghprj\v8-nuget>

**Comment by pmed** [comment]
Hi,

maybe you need to have all prerequisites installed: https://github.com/pmed/v8-nuget#how-to-build
